import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { ImagePlus, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProtectedMedia } from "@/components/ProtectedMedia";
import { CropDialog } from "@/components/CropDialog";
import { supabase } from "@/integrations/supabase/client";
import { checkSize, uploadFile } from "@/lib/media";
import { cn } from "@/lib/utils";

type Message = { id:string; member_id:string; sender_id:string; body:string|null; media_path:string|null; media_type:string|null; created_at:string };

export function ChatThread({ memberId,currentUserId,isAdmin,canSend,lockedMessage,backgroundUrl }:{memberId:string;currentUserId:string;isAdmin:boolean;canSend:boolean;lockedMessage?:string;backgroundUrl?:string|null}) {
  const qc=useQueryClient(); const [text,setText]=useState(""); const [file,setFile]=useState<File|null>(null); const [cropSrc,setCropSrc]=useState<string|null>(null); const bottomRef=useRef<HTMLDivElement>(null); const inputRef=useRef<HTMLInputElement>(null);
  const {data:limits}=useQuery({queryKey:["media-limits"],queryFn:async()=>{const {data,error}=await (supabase as any).from("media_limits").select("media_type,max_size_mb,enabled");if(error)throw error;return data??[];}});
  const {data:messages,isError}=useQuery({queryKey:["messages",memberId],queryFn:async()=>{const {data,error}=await (supabase as any).from("messages").select("id,member_id,sender_id,body,media_path,media_type,created_at").eq("member_id",memberId).order("created_at",{ascending:true});if(error)throw error;return (data??[]) as Message[];}});
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"})},[messages]); useEffect(()=>{if(canSend)inputRef.current?.focus()},[canSend,memberId]);
  const limitFor=(type:string,fallback:number)=>Number(limits?.find((x:any)=>x.media_type===type)?.max_size_mb??fallback);
  const send=useMutation({mutationFn:async()=>{let mediaPath:string|null=null;let mediaType:string|null=null;if(file){const type=file.type.startsWith("video/")?"video":file.type.startsWith("image/")?"image":"document";const row=limits?.find((x:any)=>x.media_type===type);if(row?.enabled===false)throw new Error(`${type} uploads are currently disabled`);const problem=checkSize(file,limitFor("image",10),limitFor("video",50));if(problem)throw new Error(problem);mediaPath=`${memberId}/${crypto.randomUUID()}-${file.name}`;mediaType=type;await uploadFile("chat-media",mediaPath,file)}const {error}=await (supabase as any).from("messages").insert({member_id:memberId,sender_id:currentUserId,body:text.trim()||null,media_path:mediaPath,media_type:mediaType,message_type:mediaType??"text"});if(error)throw error},onSuccess:()=>{setText("");setFile(null);void qc.invalidateQueries({queryKey:["messages",memberId]});inputRef.current?.focus()},onError:e=>toast.error(e instanceof Error?e.message:"Message not sent")});
  const remove=useMutation({mutationFn:async(id:string)=>{const {error}=await (supabase as any).from("messages").delete().eq("id",id);if(error)throw error},onSuccess:()=>void qc.invalidateQueries({queryKey:["messages",memberId]})});
  return <div className="flex h-[calc(100vh-15rem)] flex-col overflow-hidden rounded-3xl border border-border bg-card"><div className="flex-1 space-y-3 overflow-y-auto bg-cover bg-center p-4" style={backgroundUrl?{backgroundImage:`url(${backgroundUrl})`}:undefined}>{isError?<p className="text-center text-sm text-destructive">Could not load messages.</p>:null}{(messages??[]).length===0&&!isError?<p className="pt-8 text-center text-sm text-muted-foreground">No messages yet.</p>:null}{(messages??[]).map(m=>{const mine=m.sender_id===currentUserId;const fromAdmin=isAdmin?false:m.sender_id!==m.member_id;return <div key={m.id} className={cn("group flex items-end gap-2",mine&&"flex-row-reverse")}><div className={cn("max-w-[78%] rounded-2xl px-4 py-2.5 text-sm",mine?"bg-primary text-primary-foreground":"bg-secondary text-secondary-foreground")}>{m.body?<p className="whitespace-pre-wrap break-words">{m.body}</p>:null}{m.media_path?<ProtectedMedia bucket="chat-media" path={m.media_path} type={m.media_type} className="mt-2 max-h-72 w-56" allowDownload={fromAdmin&&!isAdmin} alt="Chat attachment"/>:null}<p className="mt-1 text-[10px] opacity-70">{format(new Date(m.created_at),"d MMM • HH:mm")}</p></div>{isAdmin?<Button size="icon" variant="ghost" className="opacity-0 transition-opacity group-hover:opacity-100" onClick={()=>remove.mutate(m.id)}><Trash2 className="h-3.5 w-3.5"/></Button>:null}</div>})}<div ref={bottomRef}/></div>{canSend?<form className="flex items-center gap-2 border-t border-border p-3" onSubmit={e=>{e.preventDefault();if(!text.trim()&&!file)return;send.mutate()}}><label className="flex h-10 w-10 shrink-0 cursor-pointer items-center justify-center rounded-full bg-secondary"><ImagePlus className="h-4 w-4"/><input type="file" accept="image/*,video/*" className="hidden" onChange={e=>{const f=e.target.files?.[0]??null;e.target.value="";if(f&&f.type.startsWith("image/"))setCropSrc(URL.createObjectURL(f));else setFile(f)}}/></label><Input ref={inputRef} value={text} onChange={e=>setText(e.target.value)} placeholder={file?`Attached: ${file.name}`:"Write a message…"} className="rounded-full"/><Button type="submit" size="icon" className="rounded-full" disabled={send.isPending}><Send className="h-4 w-4"/></Button></form>:<p className="border-t border-border p-4 text-center text-xs text-muted-foreground">{lockedMessage??"You cannot send messages right now."}</p>}<CropDialog open={!!cropSrc} src={cropSrc} aspect={0} title="Crop image" onCancel={()=>setCropSrc(null)} onDone={blob=>{setFile(new File([blob],`image-${Date.now()}.jpg`,{type:"image/jpeg"}));setCropSrc(null)}}/></div>;
}
